version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    expose:
      - "3306:3306"
    networks:
      - inception
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000:9000"
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    #volumes:
      #- ./nginx:/etc/nginx/conf.d
      #- ./static:/var/www/static
      #- wordpress_data:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge
