version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb-data:/var/lib/mysql/
    expose:
      - "3306"
    networks:
      - inception
    restart: unless-stopped
    env_file: 
      - .env
    healthcheck:
      test: mysqladmin ping --host=localhost -p${SQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html/wordpress/
    expose:
      - "9000"
    networks:
      - inception
    restart: unless-stopped
    env_file: 
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      - wordpress-data:/var/www/html/wordpress/
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD", "curl", "kfsSL", "https://localhost:443"]
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

# ======================== BONUSES ========================= #
# Adminer
#  adminer:
#    image: adminer
#    container_name: adminer
#    build:
#      context: requirements/bonus/adminer/
#      dockerfile: Dockerfile
#    volumes:
#    ports:
#      - "8080:8080"
#    networks:
#      - inception
#    restart: unless-stopped

# FTP Server  
#  adminer:
#    image: adminer
#    container_name: adminer
#    build:
#      context: requirements/bonus/adminer/
#      dockerfile: Dockerfile
#    volumes:
#    ports:
#      - "8080:8080"
#    networks:
#      - inception
#    restart: unless-stopped

# Additional service : Portainer
#  portainer:
#    image: portainer
#    container_name: portainer
#    build:
#      context: requirements/bonus/portainer/
#      dockerfile: Dockerfile
#    ports:
#      - "9000:9001"
#    networks:
#      - inception
#    restart: unless-stopped

# ========================================================== #

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/znogueir/data/wordpress'
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/znogueir/data/mariadb'
